---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/earthenk/public_html/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R projects $DEPLOYPATH
    - /bin/cp -R script $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp projects.html $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
